version: '3.5'
services:
  db:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
       - db:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer_container
    environment:
      ADMINER_DESIGN: pepa-linha-dark
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - db

volumes:
    db:
    adminer: